name = "CpuId"
uuid = "adafc99b-e345-5852-983c-f28acb93d879"
authors = ["Markus J. Weber"]
version = "0.3.1"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

